### ISSUE TITLE
Build command returns error

### ISSUE THREAD

**Issue by XavegX367** [thedevsbuddy/tailwind_cli#16]
I might be doing something wrong since this is the first time I try to install packages onto Flutter, but I am getting the following errors:

Running `flutter pub run tailwind_cli:build` returns:

Deprecated. Use `dart run` instead.
Building package executable... 
Built tailwind_cli:build.
Unhandled exception:
Synchronous waiting using dart:cli waitFor and C API Dart_WaitForEvent is deprecated and disabled by default. This feature will be fully removed in Dart 3.4 release. You can currently still enable it by passing --enable_deprecated_wait_for to the Dart VM. See https://dartbug.com/52121.
dart:cli-patch/cli_patch.dart 9:47                                          _waitForEvent
dart:cli/wait_for.dart 64:12                                                _WaitForUtils.waitForEvent
dart:cli/wait_for.dart 152:19                                               waitFor
package:dcli/src/util/wait_for_ex.dart 38:17                                waitForEx
package:dcli/src/functions/create_dir.dart 39:5                             createDir
package:tailwind_cli/src/utilities/Utils.dart 22:7                          Utils.makeDir
package:tailwind_cli/src/UtilityGenerator.dart 24:9                         generateTwServiceUtility
package:tailwind_cli/src/UtilityGenerator.dart 13:9                         generate
../../../.pub-cache/hosted/pub.dev/tailwind_cli-0.7.2/bin/build.dart 15:26  main
dart:isolate-patch/isolate_patch.dart 295:33                                _delayEntrypointInvocation.<fn>
dart:isolate-patch/isolate_patch.dart 184:12                                _RawReceivePort._handleMessage
package:dcli/src/util/wait_for_ex.dart 35:28                                waitForEx
package:dcli/src/functions/create_dir.dart 39:5                             createDir
package:tailwind_cli/src/utilities/Utils.dart 22:7                          Utils.makeDir
package:tailwind_cli/src/UtilityGenerator.dart 24:9                         generateTwServiceUtility
package:tailwind_cli/src/UtilityGenerator.dart 13:9                         generate
../../../.pub-cache/hosted/pub.dev/tailwind_cli-0.7.2/bin/build.dart 15:26  main
dart:isolate-patch/isolate_patch.dart 295:33                                _delayEntrypointInvocation.<fn>
dart:isolate-patch/isolate_patch.dart 184:12                                _RawReceivePort._handleMessage

If I then try to run `dart run tailwind_cli:build` I get the following:

Building package executable... (2.9s)
Built tailwind_cli:build.
Unhandled exception:
Synchronous waiting using dart:cli waitFor and C API Dart_WaitForEvent is deprecated and disabled by default. This feature will be fully removed in Dart 3.4 release. You can currently still enable it by passing --enable_deprecated_wait_for to the Dart VM. See https://dartbug.com/52121.
dart:cli-patch/cli_patch.dart 9:47                                          _waitForEvent
dart:cli/wait_for.dart 64:12                                                _WaitForUtils.waitForEvent
dart:cli/wait_for.dart 152:19                                               waitFor
package:dcli/src/util/wait_for_ex.dart 38:17                                waitForEx
package:dcli/src/functions/create_dir.dart 39:5                             createDir
package:tailwind_cli/src/utilities/Utils.dart 22:7                          Utils.makeDir
package:tailwind_cli/src/UtilityGenerator.dart 24:9                         generateTwServiceUtility
package:tailwind_cli/src/UtilityGenerator.dart 13:9                         generate
../../../.pub-cache/hosted/pub.dev/tailwind_cli-0.7.2/bin/build.dart 15:26  main
dart:isolate-patch/isolate_patch.dart 295:33                                _delayEntrypointInvocation.<fn>
dart:isolate-patch/isolate_patch.dart 184:12                                _RawReceivePort._handleMessage
package:dcli/src/util/wait_for_ex.dart 35:28                                waitForEx
package:dcli/src/functions/create_dir.dart 39:5                             createDir
package:tailwind_cli/src/utilities/Utils.dart 22:7                          Utils.makeDir
package:tailwind_cli/src/UtilityGenerator.dart 24:9                         generateTwServiceUtility
package:tailwind_cli/src/UtilityGenerator.dart 13:9                         generate
../../../.pub-cache/hosted/pub.dev/tailwind_cli-0.7.2/bin/build.dart 15:26  main
dart:isolate-patch/isolate_patch.dart 295:33                                _delayEntrypointInvocation.<fn>
dart:isolate-patch/isolate_patch.dart 184:12                                _RawReceivePort._handleMessage

**Comment by skull141209** [comment]
I also have this error

**Comment by thedevsbuddy** [comment]
@XavegX367  Thank you for pointing out the issue. As i debugged the package this error is specific to `dcli` package which is used to run commands i am working on the update and this issue will be resolved in next update.

**Comment by thedevsbuddy** [comment]
Fixed with latest commit 73cd66e
