### ISSUE TITLE
example is not working

### ISSUE THREAD

**Issue by REIZER** [thedevsbuddy/tailwind_cli#6]
lib/main.dart:42:17: Error: The getter 'TwSpacers' isn't defined for the class 'ExamplePage'.
 - 'ExamplePage' is from 'package:example/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'TwSpacers'.
                TwSpacers.sp2.widthBox,
                ^^^^^^^^^
lib/main.dart:43:77: Error: The method 'render' isn't defined for the class 'TwText Function(BuildContext)'.
 - 'TwText' is from 'package:tailwind/widgets/TwText.dart' ('tailwind/lib/widgets/TwText.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/Users/User/AppData/Local/flutter/packages/flutter/lib/src/widgets/framework.dart').Try correcting the name to the name of an existing method, or defining a method named 'render'.
                Text('Item 2 of TwWrap Widget').text.bodyText1.primaryColor.render(),
                                                                            ^^^^^^
lib/main.dart:66:15: Error: The getter 'TwSpacers' isn't defined for the class 'ExamplePage'.
 - 'ExamplePage' is from 'package:example/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'TwSpacers'.
              TwSpacers.sp3.widthBox,
              ^^^^^^^^^

**Comment by thedevsbuddy** [comment]
Fixed this issue with this commit [Example issue fixed](https://github.com/thedevsbuddy/tailwind_cli/commit/02416cd0c3104dac9949c21def760067cf5d4aae)
